repos:
  - repo: https://github.com/pycqa/flake8
    rev: '7.0.0'
    hooks:
      - id: flake8
        additional_dependencies: [
          'flake8-blind-except',
          'flake8-builtins',
          'flake8-eradicate',
          'flake8-import-order',
          'pep8-naming'
        ]
